### ISSUE TITLE
0.16, I have shooting solution

### ISSUE THREAD

**Issue by Kremnari** [MagmaMcFry/Factorissimo2#23]
I have created a stable version of this sidestepping the energy api changes.

Let's get in touch and perhaps it'll help.

Energy API solution, iterate and create multiple consumers/producers (for different flow rates), then swap them out as the user changes the limits.

The graphics were a fairly simple fix.  I didn't add Icon_size though..

I only briefly tested these fixes.

[Factorissimo2_2.1.9.zip](https://github.com/MagmaMcFry/Factorissimo2/files/1574397/Factorissimo2_2.1.9.zip)

**Comment by MagmaMcFry** [comment]
Ah, I wasn't aware the energy API changed. Thanks for the heads-up.

**Comment by Kremnari** [comment]
Might it be worthwhile to link this fix to the 0.16 discussion so others can at least test it's usability?  They can help test and report bugs until you are past your flu.

**Comment by MagmaMcFry** [comment]
I'm not so happy about that idea. First of all, you didn't add a working patch to update.lua, replacing the old interfaces with your new ones in existing saves, second of all you only "briefly tested these fixes". If you publish that version, then we'll both be up to our asses in complaints like "hey my save won't load", and it will get worse as soon as I add my own update because my update could in turn break saves that contain some of the changes you made.

Also I'd prefer if you gave me your update as a pull request instead of a zip, that way I can see exactly what you changed and add these changes to my own codebase after some 0.15 patches.
