### ISSUE TITLE
Fluid input too slow (even with bulk transfer)

### ISSUE THREAD

**Issue by Emblin13** [MagmaMcFry/Factorissimo2#29]
I have been trying desperately to pump a usable amount of water into my factory, but nothing I do works. I tried using regular pipes, with max update rate, and input or output only modes, but barely any fluid got in. Then I tried using bulk transfer pipes, and they still barely do anything!

**Comment by MagmaMcFry** [comment]
Bulk transfer pipes can contain 2500 units each, so if you set the connection mode to input and tick rate to once per tick, your theoretical transfer limit is 150000 units of fluid per second. That's a lot, and I'm sure you're not actually using that much.

However, if that bulk transfer pipe is attached to a regular pipe segment (which can only contain like 100 units of fluid), your throughput immediately decreases to maybe 20 units/tick or 1200 units/second, that's about one pump's worth. That's because Factorio's regular pipes are instant bottlenecks, just horrible at moving fluids. Vanilla fluid tanks are even worse because their settings artificially slow down fluid movement.

A good vanilla way to move fluids reeeally quickly (bypassing natural flow mechanics) is to use a whole bunch of pumps in a row, using single storage tanks or bulk transfer pipes (never two in a row) to turn corners.

Alternatively, you could try a mod like [this](https://mods.factorio.com/mod/FluidCompression) to increase throughput (but also capacity) of all vanilla fluid containers.

**Comment by Emblin13** [comment]
It turns out, my issue was throughput. My steam system was using way more than 1200 units of water per second. Thank you.
