### ISSUE TITLE
Question about the relative size of factory buildings

### ISSUE THREAD

**Issue by 012phuong** [MagmaMcFry/Factorissimo2#67]
So I've just downloaded your mod a few days ago, while both I and my friend very like this mod, they tell me this mod is kinda overpowered since the space you have to build the factory is a little bit too much when compared to the space you need to place the building down, which kinda ruin the style we're trying to achieve here. So I'm wondering is there any way that I can tweak the interior size of the building to the same size as the exterior, or at least make the exterior bigger than It used to be? I tried modifying the "inside_size" value of the layout.lua file but it didn't work

**Comment by MagmaMcFry** [comment]
Personally, I don't think this mod is overpowered since it costs more to build a factory building than to claim, fortify and pave the same amount of space in the overworld.

If you do want to try to modify this mod to fit your preferences, be aware it isn't that easy. Inside and outside size of the factory building are hardcoded in many places in the layout file, as well as in some of the main entity prototypes.
